//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Nop.Web.vn.worldsms.wcf {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IAPISMS", Namespace="http://tempuri.org/")]
    public partial class APISMS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback PushMsg2PhoneOperationCompleted;
        
        private System.Threading.SendOrPostCallback PushMsg2PhoneDLVROperationCompleted;
        
        private System.Threading.SendOrPostCallback PushMsgAdvDirectOperationCompleted;
        
        private System.Threading.SendOrPostCallback SendOTPOperationCompleted;
        
        private System.Threading.SendOrPostCallback PushMsg2ListPhoneOperationCompleted;
        
        private System.Threading.SendOrPostCallback PushMsg2ListPhoneDLVROperationCompleted;
        
        private System.Threading.SendOrPostCallback PushBulkSmsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTelcoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public APISMS() {
            this.Url = global::Nop.Web.Properties.Settings.Default.Nop_Web_vn_worldsms_wcf_APISMS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event PushMsg2PhoneCompletedEventHandler PushMsg2PhoneCompleted;
        
        /// <remarks/>
        public event PushMsg2PhoneDLVRCompletedEventHandler PushMsg2PhoneDLVRCompleted;
        
        /// <remarks/>
        public event PushMsgAdvDirectCompletedEventHandler PushMsgAdvDirectCompleted;
        
        /// <remarks/>
        public event SendOTPCompletedEventHandler SendOTPCompleted;
        
        /// <remarks/>
        public event PushMsg2ListPhoneCompletedEventHandler PushMsg2ListPhoneCompleted;
        
        /// <remarks/>
        public event PushMsg2ListPhoneDLVRCompletedEventHandler PushMsg2ListPhoneDLVRCompleted;
        
        /// <remarks/>
        public event PushBulkSmsCompletedEventHandler PushBulkSmsCompleted;
        
        /// <remarks/>
        public event GetTelcoCompletedEventHandler GetTelcoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAPISMS/PushMsg2Phone", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PushMsg2Phone([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Sender, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Msg, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Phone, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Password) {
            object[] results = this.Invoke("PushMsg2Phone", new object[] {
                        Sender,
                        Msg,
                        Phone,
                        Username,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PushMsg2PhoneAsync(string Sender, string Msg, string Phone, string Username, string Password) {
            this.PushMsg2PhoneAsync(Sender, Msg, Phone, Username, Password, null);
        }
        
        /// <remarks/>
        public void PushMsg2PhoneAsync(string Sender, string Msg, string Phone, string Username, string Password, object userState) {
            if ((this.PushMsg2PhoneOperationCompleted == null)) {
                this.PushMsg2PhoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPushMsg2PhoneOperationCompleted);
            }
            this.InvokeAsync("PushMsg2Phone", new object[] {
                        Sender,
                        Msg,
                        Phone,
                        Username,
                        Password}, this.PushMsg2PhoneOperationCompleted, userState);
        }
        
        private void OnPushMsg2PhoneOperationCompleted(object arg) {
            if ((this.PushMsg2PhoneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PushMsg2PhoneCompleted(this, new PushMsg2PhoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAPISMS/PushMsg2PhoneDLVR", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PushMsg2PhoneDLVR([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Sender, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Msg, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Phone, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string RequestId, int idclient, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idclientSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Password) {
            object[] results = this.Invoke("PushMsg2PhoneDLVR", new object[] {
                        Sender,
                        Msg,
                        Phone,
                        RequestId,
                        idclient,
                        idclientSpecified,
                        Username,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PushMsg2PhoneDLVRAsync(string Sender, string Msg, string Phone, string RequestId, int idclient, bool idclientSpecified, string Username, string Password) {
            this.PushMsg2PhoneDLVRAsync(Sender, Msg, Phone, RequestId, idclient, idclientSpecified, Username, Password, null);
        }
        
        /// <remarks/>
        public void PushMsg2PhoneDLVRAsync(string Sender, string Msg, string Phone, string RequestId, int idclient, bool idclientSpecified, string Username, string Password, object userState) {
            if ((this.PushMsg2PhoneDLVROperationCompleted == null)) {
                this.PushMsg2PhoneDLVROperationCompleted = new System.Threading.SendOrPostCallback(this.OnPushMsg2PhoneDLVROperationCompleted);
            }
            this.InvokeAsync("PushMsg2PhoneDLVR", new object[] {
                        Sender,
                        Msg,
                        Phone,
                        RequestId,
                        idclient,
                        idclientSpecified,
                        Username,
                        Password}, this.PushMsg2PhoneDLVROperationCompleted, userState);
        }
        
        private void OnPushMsg2PhoneDLVROperationCompleted(object arg) {
            if ((this.PushMsg2PhoneDLVRCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PushMsg2PhoneDLVRCompleted(this, new PushMsg2PhoneDLVRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAPISMS/PushMsgAdvDirect", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PushMsgAdvDirect([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Sender, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Msg, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Phone, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Password) {
            object[] results = this.Invoke("PushMsgAdvDirect", new object[] {
                        Sender,
                        Msg,
                        Phone,
                        Username,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PushMsgAdvDirectAsync(string Sender, string Msg, string Phone, string Username, string Password) {
            this.PushMsgAdvDirectAsync(Sender, Msg, Phone, Username, Password, null);
        }
        
        /// <remarks/>
        public void PushMsgAdvDirectAsync(string Sender, string Msg, string Phone, string Username, string Password, object userState) {
            if ((this.PushMsgAdvDirectOperationCompleted == null)) {
                this.PushMsgAdvDirectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPushMsgAdvDirectOperationCompleted);
            }
            this.InvokeAsync("PushMsgAdvDirect", new object[] {
                        Sender,
                        Msg,
                        Phone,
                        Username,
                        Password}, this.PushMsgAdvDirectOperationCompleted, userState);
        }
        
        private void OnPushMsgAdvDirectOperationCompleted(object arg) {
            if ((this.PushMsgAdvDirectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PushMsgAdvDirectCompleted(this, new PushMsgAdvDirectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAPISMS/SendOTP", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SendOTP([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Sender, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Msg, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Phone, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Password) {
            object[] results = this.Invoke("SendOTP", new object[] {
                        Sender,
                        Msg,
                        Phone,
                        Username,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SendOTPAsync(string Sender, string Msg, string Phone, string Username, string Password) {
            this.SendOTPAsync(Sender, Msg, Phone, Username, Password, null);
        }
        
        /// <remarks/>
        public void SendOTPAsync(string Sender, string Msg, string Phone, string Username, string Password, object userState) {
            if ((this.SendOTPOperationCompleted == null)) {
                this.SendOTPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendOTPOperationCompleted);
            }
            this.InvokeAsync("SendOTP", new object[] {
                        Sender,
                        Msg,
                        Phone,
                        Username,
                        Password}, this.SendOTPOperationCompleted, userState);
        }
        
        private void OnSendOTPOperationCompleted(object arg) {
            if ((this.SendOTPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendOTPCompleted(this, new SendOTPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAPISMS/PushMsg2ListPhone", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PushMsg2ListPhone([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Sender, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Msg, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")] string[] Phone, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Password) {
            object[] results = this.Invoke("PushMsg2ListPhone", new object[] {
                        Sender,
                        Msg,
                        Phone,
                        Username,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PushMsg2ListPhoneAsync(string Sender, string Msg, string[] Phone, string Username, string Password) {
            this.PushMsg2ListPhoneAsync(Sender, Msg, Phone, Username, Password, null);
        }
        
        /// <remarks/>
        public void PushMsg2ListPhoneAsync(string Sender, string Msg, string[] Phone, string Username, string Password, object userState) {
            if ((this.PushMsg2ListPhoneOperationCompleted == null)) {
                this.PushMsg2ListPhoneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPushMsg2ListPhoneOperationCompleted);
            }
            this.InvokeAsync("PushMsg2ListPhone", new object[] {
                        Sender,
                        Msg,
                        Phone,
                        Username,
                        Password}, this.PushMsg2ListPhoneOperationCompleted, userState);
        }
        
        private void OnPushMsg2ListPhoneOperationCompleted(object arg) {
            if ((this.PushMsg2ListPhoneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PushMsg2ListPhoneCompleted(this, new PushMsg2ListPhoneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAPISMS/PushMsg2ListPhoneDLVR", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PushMsg2ListPhoneDLVR([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Sender, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Msg, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Stel.WCF.APISMS.WorldSMS2._0")] ListPhone[] Phone, int idclient, [System.Xml.Serialization.XmlIgnoreAttribute()] bool idclientSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Password) {
            object[] results = this.Invoke("PushMsg2ListPhoneDLVR", new object[] {
                        Sender,
                        Msg,
                        Phone,
                        idclient,
                        idclientSpecified,
                        Username,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PushMsg2ListPhoneDLVRAsync(string Sender, string Msg, ListPhone[] Phone, int idclient, bool idclientSpecified, string Username, string Password) {
            this.PushMsg2ListPhoneDLVRAsync(Sender, Msg, Phone, idclient, idclientSpecified, Username, Password, null);
        }
        
        /// <remarks/>
        public void PushMsg2ListPhoneDLVRAsync(string Sender, string Msg, ListPhone[] Phone, int idclient, bool idclientSpecified, string Username, string Password, object userState) {
            if ((this.PushMsg2ListPhoneDLVROperationCompleted == null)) {
                this.PushMsg2ListPhoneDLVROperationCompleted = new System.Threading.SendOrPostCallback(this.OnPushMsg2ListPhoneDLVROperationCompleted);
            }
            this.InvokeAsync("PushMsg2ListPhoneDLVR", new object[] {
                        Sender,
                        Msg,
                        Phone,
                        idclient,
                        idclientSpecified,
                        Username,
                        Password}, this.PushMsg2ListPhoneDLVROperationCompleted, userState);
        }
        
        private void OnPushMsg2ListPhoneDLVROperationCompleted(object arg) {
            if ((this.PushMsg2ListPhoneDLVRCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PushMsg2ListPhoneDLVRCompleted(this, new PushMsg2ListPhoneDLVRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAPISMS/PushBulkSms", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PushBulkSms([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Sender, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Stel.WCF.APISMS.WorldSMS2._0")] DataSms[] data, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Password) {
            object[] results = this.Invoke("PushBulkSms", new object[] {
                        Sender,
                        data,
                        Username,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PushBulkSmsAsync(string Sender, DataSms[] data, string Username, string Password) {
            this.PushBulkSmsAsync(Sender, data, Username, Password, null);
        }
        
        /// <remarks/>
        public void PushBulkSmsAsync(string Sender, DataSms[] data, string Username, string Password, object userState) {
            if ((this.PushBulkSmsOperationCompleted == null)) {
                this.PushBulkSmsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPushBulkSmsOperationCompleted);
            }
            this.InvokeAsync("PushBulkSms", new object[] {
                        Sender,
                        data,
                        Username,
                        Password}, this.PushBulkSmsOperationCompleted, userState);
        }
        
        private void OnPushBulkSmsOperationCompleted(object arg) {
            if ((this.PushBulkSmsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PushBulkSmsCompleted(this, new PushBulkSmsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IAPISMS/GetTelco", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetTelco([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Phone, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Username, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string Password) {
            object[] results = this.Invoke("GetTelco", new object[] {
                        Phone,
                        Username,
                        Password});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTelcoAsync(string Phone, string Username, string Password) {
            this.GetTelcoAsync(Phone, Username, Password, null);
        }
        
        /// <remarks/>
        public void GetTelcoAsync(string Phone, string Username, string Password, object userState) {
            if ((this.GetTelcoOperationCompleted == null)) {
                this.GetTelcoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTelcoOperationCompleted);
            }
            this.InvokeAsync("GetTelco", new object[] {
                        Phone,
                        Username,
                        Password}, this.GetTelcoOperationCompleted, userState);
        }
        
        private void OnGetTelcoOperationCompleted(object arg) {
            if ((this.GetTelcoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTelcoCompleted(this, new GetTelcoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Stel.WCF.APISMS.WorldSMS2._0")]
    public partial class ListPhone {
        
        private string phoneField;
        
        private string requestIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RequestId {
            get {
                return this.requestIdField;
            }
            set {
                this.requestIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Stel.WCF.APISMS.WorldSMS2._0")]
    public partial class DataSms {
        
        private string messageField;
        
        private string phoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void PushMsg2PhoneCompletedEventHandler(object sender, PushMsg2PhoneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PushMsg2PhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PushMsg2PhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void PushMsg2PhoneDLVRCompletedEventHandler(object sender, PushMsg2PhoneDLVRCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PushMsg2PhoneDLVRCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PushMsg2PhoneDLVRCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void PushMsgAdvDirectCompletedEventHandler(object sender, PushMsgAdvDirectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PushMsgAdvDirectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PushMsgAdvDirectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void SendOTPCompletedEventHandler(object sender, SendOTPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendOTPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SendOTPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void PushMsg2ListPhoneCompletedEventHandler(object sender, PushMsg2ListPhoneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PushMsg2ListPhoneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PushMsg2ListPhoneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void PushMsg2ListPhoneDLVRCompletedEventHandler(object sender, PushMsg2ListPhoneDLVRCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PushMsg2ListPhoneDLVRCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PushMsg2ListPhoneDLVRCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void PushBulkSmsCompletedEventHandler(object sender, PushBulkSmsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PushBulkSmsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PushBulkSmsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GetTelcoCompletedEventHandler(object sender, GetTelcoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTelcoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTelcoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591